CREATE TABLE `blog` (
  `id` INT(11) PRIMARY KEY AUTO_INCREMENT,
  `title` VARCHAR(200) NOT NULL ,
	`tag` VARCHAR(20) DEFAULT NULL ,
	`pic` VARCHAR(100) NOT NULL,
  `content` VARCHAR(400) DEFAULT NULL ,
  `date` DATETIME DEFAULT NULL 
)

CREATE TABLE `users` (
  `id` INT(11)  PRIMARY KEY  AUTO_INCREMENT,
  `username` VARCHAR(100) NOT NULL ,
  `password` VARCHAR(16) NOT NULL ,
  `email` VARCHAR(100) DEFAULT NULL ,
  `image` VARCHAR(100) NOT NULL
)

